"""Fixed financial metrics module for backtest evaluation.

All 9 core metrics plus compute_all_metrics aggregate function.
This module is FIXED code (not regenerated by Claude) -- it is the trust
anchor for all downstream calculations.

Functions accept numpy arrays (not pandas Series). Conversion happens
in compute_all_metrics if needed.
"""

from __future__ import annotations

import math
from typing import Any

import numpy as np


def sharpe_ratio(
    returns: np.ndarray,
    risk_free_rate: float = 0.0,
    trading_days: int = 252,
) -> float:
    """Annualized Sharpe ratio.

    Args:
        returns: Array of daily returns (e.g., 0.01 for 1%).
        risk_free_rate: Annual risk-free rate (default 0).
        trading_days: Trading days per year for annualization.

    Returns:
        Sharpe ratio, or NaN if insufficient data or zero volatility.
    """
    if len(returns) < 2:
        return float("nan")

    daily_rf = risk_free_rate / trading_days
    excess = returns - daily_rf
    std = np.std(excess, ddof=1)

    if std < 1e-12:
        return float("nan")

    return float(np.mean(excess) / std * np.sqrt(trading_days))


def sortino_ratio(
    returns: np.ndarray,
    risk_free_rate: float = 0.0,
    trading_days: int = 252,
) -> float:
    """Annualized Sortino ratio (downside deviation only).

    Args:
        returns: Array of daily returns.
        risk_free_rate: Annual risk-free rate (default 0).
        trading_days: Trading days per year for annualization.

    Returns:
        Sortino ratio, or NaN if insufficient data or no downside deviation.
    """
    if len(returns) < 2:
        return float("nan")

    daily_rf = risk_free_rate / trading_days
    excess = returns - daily_rf
    downside = excess[excess < 0]

    if len(downside) == 0:
        return float("nan")

    downside_std = np.sqrt(np.mean(downside**2))

    if downside_std == 0.0:
        return float("nan")

    return float(np.mean(excess) / downside_std * np.sqrt(trading_days))


def calmar_ratio(
    returns: np.ndarray,
    equity_curve: np.ndarray,
    trading_days: int = 252,
) -> float:
    """Calmar ratio: annualized return / abs(max drawdown).

    Args:
        returns: Array of daily returns.
        equity_curve: Equity curve array.
        trading_days: Trading days per year for annualization.

    Returns:
        Calmar ratio, or NaN if no drawdown or insufficient data.
    """
    if len(returns) == 0 or len(equity_curve) == 0:
        return float("nan")

    dd = max_drawdown(equity_curve)

    if dd == 0.0:
        return float("nan")

    annualized_return = float(np.mean(returns) * trading_days)
    return annualized_return / abs(dd)


def max_drawdown(equity_curve: np.ndarray) -> float:
    """Maximum drawdown as a negative fraction (e.g., -0.25 = 25% drop).

    Args:
        equity_curve: Array of equity values.

    Returns:
        Max drawdown (negative or zero). 0.0 for empty/single/increasing curves.
    """
    if len(equity_curve) <= 1:
        return 0.0

    running_max = np.maximum.accumulate(equity_curve)
    drawdowns = (equity_curve - running_max) / running_max
    return float(np.min(drawdowns))


def win_rate(trades: list[dict[str, Any]]) -> float:
    """Fraction of winning trades.

    Args:
        trades: List of trade dicts, each with 'pnl' key.

    Returns:
        Win rate in [0, 1]. 0.0 for empty trades.
    """
    if not trades:
        return 0.0

    winners = sum(1 for t in trades if t["pnl"] > 0)
    return winners / len(trades)


def profit_factor(trades: list[dict[str, Any]]) -> float:
    """Gross profit / gross loss.

    Args:
        trades: List of trade dicts, each with 'pnl' key.

    Returns:
        Profit factor. inf if winners but no losers. 0.0 if no winners or empty.
    """
    if not trades:
        return 0.0

    gross_profit = sum(t["pnl"] for t in trades if t["pnl"] > 0)
    gross_loss = sum(t["pnl"] for t in trades if t["pnl"] < 0)

    if gross_loss == 0:
        return float("inf") if gross_profit > 0 else 0.0

    return gross_profit / abs(gross_loss)


def expectancy(trades: list[dict[str, Any]]) -> float:
    """Average PnL per trade.

    Args:
        trades: List of trade dicts, each with 'pnl' key.

    Returns:
        Mean PnL. 0.0 for empty trades.
    """
    if not trades:
        return 0.0

    return sum(t["pnl"] for t in trades) / len(trades)


def trade_count(trades: list[dict[str, Any]]) -> int:
    """Number of trades.

    Args:
        trades: List of trade dicts.

    Returns:
        len(trades).
    """
    return len(trades)


def net_pnl(trades: list[dict[str, Any]]) -> float:
    """Total PnL across all trades.

    Args:
        trades: List of trade dicts, each with 'pnl' key.

    Returns:
        Sum of all pnl values. 0.0 for empty trades.
    """
    if not trades:
        return 0.0

    return sum(t["pnl"] for t in trades)


def compute_all_metrics(
    trades: list[dict[str, Any]] | None = None,
    equity_curve: np.ndarray | None = None,
    daily_returns: np.ndarray | None = None,
    trading_days: int = 252,
    risk_free_rate: float = 0.0,
    initial_capital: float = 10000.0,
) -> dict[str, float]:
    """Compute all 9 metrics from trades and/or daily returns.

    With trade log input: derives daily returns from trades, computes equity
    curve, returns all 9 metrics.

    With daily_returns input: computes equity curve from returns, returns ratio
    metrics (Sharpe, Sortino, Calmar, MaxDD) and 0/NaN for trade-based metrics.

    Args:
        trades: List of trade dicts with 'pnl' key (and optionally other fields).
        equity_curve: Pre-computed equity curve (overrides internal computation).
        daily_returns: Array of daily returns.
        trading_days: Trading days per year for annualization.
        risk_free_rate: Annual risk-free rate.
        initial_capital: Starting capital for equity curve computation.

    Returns:
        Dict with keys: sharpe_ratio, sortino_ratio, calmar_ratio, max_drawdown,
        win_rate, profit_factor, expectancy, trade_count, net_pnl.
    """
    # Derive equity curve and returns from trades if provided
    if trades is not None and len(trades) > 0:
        pnls = np.array([t["pnl"] for t in trades])
        cum_pnl = np.cumsum(pnls)
        eq = initial_capital + cum_pnl

        if equity_curve is None:
            equity_curve = eq

        if daily_returns is None:
            # Derive daily returns from equity curve
            eq_with_start = np.concatenate([[initial_capital], eq])
            daily_returns = np.diff(eq_with_start) / eq_with_start[:-1]

    # Derive equity from daily returns if only returns provided
    elif daily_returns is not None and len(daily_returns) > 0:
        if equity_curve is None:
            equity_curve = initial_capital * np.cumprod(1.0 + daily_returns)

    # Compute ratio-based metrics
    if daily_returns is not None and len(daily_returns) > 0:
        sr = sharpe_ratio(daily_returns, risk_free_rate, trading_days)
        so = sortino_ratio(daily_returns, risk_free_rate, trading_days)
    else:
        sr = float("nan")
        so = float("nan")

    if equity_curve is not None and len(equity_curve) > 0:
        dd = max_drawdown(equity_curve)
        if daily_returns is not None and len(daily_returns) > 0:
            cal = calmar_ratio(daily_returns, equity_curve, trading_days)
        else:
            cal = float("nan")
    else:
        dd = 0.0
        cal = float("nan")

    # Compute trade-based metrics
    _trades = trades if trades is not None else []
    wr = win_rate(_trades)
    pf = profit_factor(_trades)
    exp = expectancy(_trades)
    tc = trade_count(_trades)
    np_val = net_pnl(_trades)

    return {
        "sharpe_ratio": sr,
        "sortino_ratio": so,
        "calmar_ratio": cal,
        "max_drawdown": dd,
        "win_rate": wr,
        "profit_factor": pf,
        "expectancy": exp,
        "trade_count": tc,
        "net_pnl": np_val,
    }
